theme: jekyll-theme-cayman
title: Fish Tank Simulation
description: Simulate a fish tank with violent, hungry fishes! The Blessed Fish may come and heal fishes that attack him, otherwise it's each fish for himself.
